name: turistando
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.0.5
  percent_indicator: ^2.1.1+1
  image_picker: ^0.6.4
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/